### PR TITLE
Document the `live` option

### PR DESCRIPTION
**Pull request by tomekwi**
Hi, cool option – but I’ve only found it through reading the source! Should I mention it anywhere else than the readme?

### CODE REVIEW

**Comment by tomekwi** [comment]
I signed it!

**Comment by mbleigh** [comment]
Thanks for the PR! We're actually deprecating the `--live` option in favor of supporting easier integration of Superstatic into an existing livereload or browsersync workflow. Because of that, I'm going to go ahead and close this.

**Comment by tomekwi** [comment]
I actually loved the simplicity of setup – one command and you’re done.

But fair enough. I appreciate that composing a custom toolchain is much a more powerful option.

Is the transition documented anywhere?

**Comment by tomekwi** [comment]
> Is the transition documented anywhere?

For anyone else wondering here’s a hint: https://github.com/firebase/superstatic/issues/145#issuecomment-81285322.

**Pull request closed without merging**
