### PR TITLE
Disallow upward tree traversal in Windows.

### PR DESCRIPTION
**Pull request by mbleigh**
Internal bug id: 74001072

### CODE REVIEW

**Comment by abehaskins** [comment]
This is still being reported as a vulnerability from [this report](https://nodesecurity.io/advisories/652). Anyone know how to mark this as fixed?

**Comment by ChALkeR** [comment]
@abehaskins It is not fixed, a patched version of superstatic was never released.

**Comment by ChALkeR** [comment]
@abehaskins I personally suggest to switch to some maintained static file server instead of `superstatic`.

**Comment by ChALkeR** [comment]
@abehaskins Ah, sorry. I was answering from the phone and did not notice that you are a member of @firebase then — I assumed that you were a consumer of `superstatic`.

So, the answer is — release a fixed version of `superstatic` and wait for the datasets to be updated.

They do not include a `fixed` field atm because this was dislosed by @firebase and left for a long time without actual fixed version being released.
E.g. see the discussion at https://github.com/nodejs/security-wg/pull/247#discussion_r184914574. The normal process includes landing those entries when an issue is fixed and disclosed or when there is no response from authors, but in this case @firebase disclosed this without releasing a fix, so it was added to the databse by Node.js Security WG likewise, after a confirmation from Google that this can be treated as disclosed.

You can also try filing a PR to https://github.com/nodejs/security-wg after releasing the fix. That's not the direct location which npm sources their data from, but it's where this vuln entry originates from so other datasets (including npm's one) probably would notice the update shortly after.

**Comment by ChALkeR** [comment]
Also, my note from the original report (I am unsure if it was passed down here):
> That fix seems to work, but the recommended solution to prevent path traversal is to resolve the path and then check that the resolved path is inside the base path.
...
> Are there plans for implementing the recommended solution of additinally checking the actual resolved path?

**Pull request merged**
